
package com.epam.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailWebService", targetNamespace = "http://soap.web.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.epam.web.soap.Letter>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLetters", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetAllLetters")
    @ResponseWrapper(localName = "getAllLettersResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetAllLettersResponse")
    public List<Letter> getAllLetters()
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.epam.web.soap.Letter>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLetterBySubject", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetLetterBySubject")
    @ResponseWrapper(localName = "getLetterBySubjectResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetLetterBySubjectResponse")
    public List<Letter> getLetterBySubject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.epam.web.soap.Letter>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLetterByEmail", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetLetterByEmail")
    @ResponseWrapper(localName = "getLetterByEmailResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetLetterByEmailResponse")
    public List<Letter> getLetterByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteLetterBySubject", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.DeleteLetterBySubject")
    @ResponseWrapper(localName = "deleteLetterBySubjectResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.DeleteLetterBySubjectResponse")
    public void deleteLetterBySubject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws CsvDataTypeMismatchException_Exception
     * @throws CsvRequiredFieldEmptyException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "sendLetter", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.SendLetter")
    @ResponseWrapper(localName = "sendLetterResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.SendLetterResponse")
    public void sendLetter(
        @WebParam(name = "arg0", targetNamespace = "")
        Letter arg0)
        throws CsvDataTypeMismatchException_Exception, CsvRequiredFieldEmptyException_Exception, IOException_Exception
    ;

}
